before_script:
- bash ci/docker_install.sh > /dev/null
- bin/composer install --dev

stages:
- build

phpunit:php5.6:
  stage: build
  image: php:5.6
  script:
  - bin/composer install --dev
    
phpunit:php7.0:
  stage: build
  image: php:7.0
  script:
  - bin/composer install --dev

phpunit:php7.1:
  stage: build
  image: php:7.1
  script:
  - bin/composer install --dev
