<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'Tools\Controller\CronController'                             => __DIR__ . '/src/Tools/Crontroller/CronController.php',
	'Tools\Module'                                                => __DIR__ . '/src/Tools/Module.php'
);
