<?php
/**
 * Empty view
 *
 * @category  view
 * @package   view\tools\caches
 * @author    David Dattée <david.dattee@gmail.com>
 * @copyright 2016 David Dattée
 * @license   MIT License (MIT)
 */
?>
<div class="alert <?php echo($this->result ? 'alert-success' : 'alert-danger') ?>">
    <code><?php echo $this->folder ?></code><br>
    <?php if ($this->result) { ?>
        Le cache du dossier à bien été vidé.<br>
        <?php echo $this->spared ?> Mo ont été libérés.
    <?php } else { ?>
        Une erreur s'est produite lors du vidage du dossier. <br>
        Le cache n'a pas été vidé.<br>
        <pre>
        <?php echo $this->msg ?>
        </pre>
    <?php } ?>
</div>