<?php
/**
 * clean layout
 *
 * @category  view
 * @package   view\layout
 * @author    David Dattée <david.dattee@gmail.com>
 * @copyright 2016 David Dattée
 * @license   MIT License (MIT)
 */
?>
<?php echo $this->doctype(); ?>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Gears ' . $this->translate('Front App'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/modules/tools/img/favicon.png'))
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
        ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
    ?>

    <?php
    echo $this->headScript()
        ->prependFile('//oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js', 'text/javascript');
    ?>

</head>
<body class="">
<header>
    <?php echo $this->partial('partials/_toolsbar.phtml'); ?>
</header>
<div app="cron">
    <div class="container">
        <?php echo $this->content; ?>
    </div>
</div>
<!-- Scripts -->
<?php
echo $this->headScript()
    ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'text/javascript');
?>
<?php echo $this->inlineScript(); ?>
</body>
</html>
